image: alpine:latest

# TODO Bulid the html in the CI

# A no-op that tells gitlab to serve the content of the public directory
# see https://gitlab.com/pages/plain-html/blob/master/.gitlab-ci.yml
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
